# Generated by Django 5.1.7 on 2025-03-07 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0002_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, default='https://images.unsplash.com/photo-1416339306562-f3d12fefd36f', max_length=500, null=True),
        ),
    ]
